server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:4321/envel
    username: postgres_user
    password: postgres_password
  jpa:
    properties:
      hibernate:
        default_scheme:audit
graphql:
  spqr:
    gui:
      enabled: true
      endpoint: /gui