server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:4321/envel
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        default_schema: audit
  #    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:5001/auth/realms/envel

graphql:
  spqr:
    gui:
      enabled: true
      endpoint: /gui