version: "3.9"
volumes:
  postgres_volume: {}

services:
  db:
    container_name: envel_postgres
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: envel
    ports:
      - "4321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data